In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

/Users/hadrienmorand/.pyenv/versions/3.8.6/envs/mush_me/lib/python3.8/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [106]:
data = pd.read_csv('DanishFungi2020_train_metadata_DEV.csv')
data

,gbifID,eventDate,year,month,day,countryCode,locality,identifiedBy,taxonID,scientificName,...,Substrate,rightsHolder,Latitude,Longitude,CoorUncert,Habitat,image_path,class_id,genus_id,family_id
0,2238546328,2018-04-16T00:00:00,2018.0,4.0,16.0,DK,Ulvedal Plantage,Ulfva Melchior Hvidegaard,30872.0,Ramalina farinacea (L.) Ach.,...,bark of living trees,Ulfva Melchior Hvidegaard,56.299706,9.258110,50.0,Mixed woodland (with coniferous and deciduous ...,/Datasets/DF20/2238546328-30620.jpg,1273,453,142
1,2558871973,2020-01-03T00:00:00,2020.0,1.0,3.0,DK,Slotshegn,Thomas Læssøe,15256.0,Hysterium acuminatum Fr.,...,dead wood (including bark),Ole Martin,55.861899,11.975973,50.0,Deciduous woodland,/Datasets/DF20/2558871973-53941.jpg,708,246,82
2,2238503501,2017-08-22T00:00:00,2017.0,8.0,22.0,DK,Petersborg Strandenge,Per Taudal Poulsen,61200.0,Gliophorus perplexus (A.H.Sm. & Hesler) Kovalenko,...,soil,Per Taudal Poulsen,56.975158,9.285525,75.0,natural grassland,/Datasets/DF20/2238503501-245559.jpg,535,186,76
3,2446759075,2019-10-26T00:00:00,2019.0,10.0,26.0,DK,Klintebjerg,Susanne Rabenborg,30530.0,Lecidella scabra (Taylor) Hertel & Leuckert,...,stone,Susanne Rabenborg,55.960242,11.583103,15.0,gravel or clay pit,/Datasets/DF20/2446759075-197643.jpg,832,276,87
4,2238472345,2016-08-21T00:00:00,2016.0,8.0,21.0,DK,Blåbjerg,Tom Smidth,63728.0,"Russula fragilis Fr., 1838",...,soil,Tom Smidth,55.742985,8.250188,50.0,Mixed woodland (with coniferous and deciduous ...,/Datasets/DF20/2238472345-167057.jpg,1338,476,152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266339,2238575234,2018-10-24T00:00:00,2018.0,10.0,24.0,DK,Glostrup Hospital,Thomas Kehlet,12634.0,Cortinarius subpurpurascens (Batsch) Fr.,...,soil,Thomas Kehlet,55.673710,12.391151,5.0,park/churchyard,/Datasets/DF20/2238575234-110923.jpg,327,111,40
266340,2238488482,2017-04-13T00:00:00,2017.0,4.0,13.0,DK,Husby Klitplantage,Morten Christensen,14064.0,Fomitopsis pinicola (Sw.) P.Karst.,...,dead wood (including bark),Morten Christensen,56.287286,8.172253,25.0,coniferous woodland/plantation,/Datasets/DF20/2238488482-318617.jpg,492,176,56
266341,2856918355,2020-09-05T00:00:00,2020.0,9.0,5.0,DK,Lynæs,Thomas Kehlet,21632.0,Lycoperdon pratense Pers.,...,soil,Thomas Kehlet,55.952711,11.876095,5.0,gravel or clay pit,/Datasets/DF20/2856918355-210091.jpg,886,302,2
266342,2238432527,2009-10-14T00:00:00,2009.0,10.0,14.0,DK,Hylke,Jens Mårbjerg,20599.0,Steccherinum fimbriatum (Pers.) J.Erikss.,...,wood,Jens Mårbjerg,56.006130,9.928160,25.0,Unmanaged deciduous woodland,/Datasets/DF20/2238432527-313815.jpg,1427,504,100
266343,2238546801,2018-05-23T00:00:00,2018.0,5.0,23.0,DK,Roskilde Øst,Tom Smidth,30766.0,Physcia adscendens (Th.Fr.) H.Olivier,...,bark of living trees,Tom Smidth,55.643983,12.100445,25.0,park/churchyard,/Datasets/DF20/2238546801-252985.jpg,1160,408,130

In [107]:
data[data['CoorUncert'].isna()].count()

gbifID                  3460
eventDate               3456
year                    3456
month                   3456
day                     3456
countryCode             3460
locality                3460
identifiedBy            3441
taxonID                 3460
scientificName          3460
kingdom                 3460
phylum                  3460
class                   3460
order                   3460
family                  3460
genus                   3460
specificEpithet         3460
infraspecificEpithet       0
taxonRank               3460
species                 3460
level0Gid               3437
level0Name              3437
level1Gid               3437
level1Name              3437
level2Gid               3437
level2Name              3437
ImageUniqueID           3460
image_url               3460
Substrate               3456
rightsHolder            3460
Latitude                3460
Longitude               3460
CoorUncert                 0
Habitat                 3455
image_path              3460
class_id                3460
genus_id                3460
family_id               3460
dtype: int64

In [108]:
data = data[data['kingdom']=='Fungi']

data.drop(columns=['image_path','rightsHolder','image_url',
                   'identifiedBy','infraspecificEpithet',
                  'level0Gid','level0Name', 'level1Gid', 'level1Name', 
                   'level2Gid', 'level2Name','gbifID','kingdom','taxonRank'], inplace=True)

data.isnull().sum().sort_values(ascending=False)/len(data)

/Users/hadrienmorand/.pyenv/versions/3.8.6/envs/mush_me/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

CoorUncert         0.013085
Substrate          0.005169
Habitat            0.003669
order              0.000596
locality           0.000262
class              0.000110
species            0.000110
eventDate          0.000061
month              0.000061
day                0.000061
year               0.000061
genus_id           0.000000
class_id           0.000000
Longitude          0.000000
Latitude           0.000000
genus              0.000000
ImageUniqueID      0.000000
specificEpithet    0.000000
family             0.000000
phylum             0.000000
scientificName     0.000000
taxonID            0.000000
countryCode        0.000000
family_id          0.000000
dtype: float64

In [109]:
## Select columns, excluding objects
input_cat = data.select_dtypes(exclude=["float64","int64"])
## Store the column names in a variable
features = input_cat.columns
## Loop over all the selected columns to display value_counts
for feature in features:
   print(data[feature].value_counts())

2020-10-03T00:00:00    1007
2020-10-31T00:00:00    1007
2020-10-04T00:00:00    1000
2020-10-11T00:00:00     900
2020-10-09T00:00:00     842
                       ...
2016-06-04T00:00:00       1
2009-02-23T00:00:00       1
1981-08-21T00:00:00       1
2007-07-26T00:00:00       1
2005-10-24T00:00:00       1
Name: eventDate, Length: 4975, dtype: int64
DK    261040
SE      1149
ES       145
GR       137
DE       135
CZ       122
GB       101
NO        99
PL        97
IS        47
IT        35
FI        33
NL        30
FR        26
GL        17
US        14
AU        13
SJ         8
HU         7
HR         6
PT         6
CA         4
JP         3
FO         3
AT         2
GA         2
AL         1
RU         1
CR         1
NP         1
Name: countryCode, dtype: int64
Store Hareskov           2751
Hegedal                  2585
Rantzausminde            2309
Hobro                    2191
Vestskoven, København    1965
                         ...
Ranum By                    1
Græsholmene Skov            1
Vindebæk                    1
Fjellerup Mark              1
Bollalt                     1
Name: locality, Length: 8831, dtype: int64
Trametes versicolor (L.) Lloyd                                       1722
Fomitopsis pinicola (Sw.) P.Karst.                                   1569
Hypholoma fasciculare (Huds.) P.Kumm., 1871                          1472
Pluteus cervinus (Schaeff.) P.Kumm.                                  1228
Fomes fomentarius (L.) Fr., 1849                                     1185
                                                                     ...
Lycoperdon mammiforme Pers.                                            28
Cudonia circinans (Pers.) Fr.                                          28
Clavaria zollingeri Lév.                                               28
Cuphophyllus fuscescens (Bres.) Bon                                    28
Heteroradulum deglubens (Berk. & Broome) Spirin & Malysheva, 2017      28
Name: scientificName, Length: 1576, dtype: int64
Basidiomycota    224148
Ascomycota        39031
Zygomycota          106
Name: phylum, dtype: int64
Agaricomycetes        217875
Lecanoromycetes        16389
Sordariomycetes         8352
Leotiomycetes           6211
Pezizomycetes           5428
Pucciniomycetes         2431
Dacrymycetes            1843
Tremellomycetes         1503
Geoglossomycetes        1264
Dothideomycetes          498
Eurotiomycetes           343
Taphrinomycetes          337
Ustilaginomycetes        158
Exobasidiomycetes        152
Orbiliomycetes           130
Atractiellomycetes       118
Mucoromycetes            106
Microbotryomycetes        68
Arthoniomycetes           50
Name: class, dtype: int64
Agaricales          120857
Polyporales          30618
Russulales           22982
Boletales            19216
Lecanorales          11324
Hymenochaetales       9256
Xylariales            5522
Pezizales             5428
Helotiales            4963
Cantharellales        4346
Auriculariales        3790
Teloschistales        2556
Pucciniales           2378
Hypocreales           2262
Dacrymycetales        1843
Tremellales           1503
Gomphales             1461
Thelephorales         1352
Geoglossales          1264
Geastrales             992
Phallales              950
Peltigerales           923
Gloeophyllales         801
Corticiales            732
Rhytismatales          683
Pertusariales          452
Ostropales             358
Taphrinales            337
Candelariales          315
Erysiphales            297
Acarosporales          290
Pleosporales           276
Leotiales              268
Sordariales            260
Atheliales             229
Trechisporales         162
Urocystidales          158
Orbiliales             130
Coronophorales         128
Atractiellales         118
Exobasidiales          111
Eurotiales             108
Mucorales              106
Baeomycetales           97
Boliniales              92
Diaporthales            88
Hysteriales             88
Sebacinales             81
Umbilicariales          74
Verrucariales           70
Microbotryales          68
Platygloeales           53
Arthoniales             50
Patellariales           50
Amylocorticiales        50
Capnodiales             48
Entylomatales           41
Onygenales              37
Acrospermales           36
Name: order, dtype: int64
Russulaceae          17228
Agaricaceae          14256
Tricholomataceae     14120
Polyporaceae         12558
Boletaceae           12230
                     ...
Stephanosporaceae       32
Coniocybaceae           32
Raveneliaceae           32
Caloscyphaceae          29
Collemataceae           28
Name: family, Length: 181, dtype: int64
Russula          10232
Mycena            9325
Cortinarius       7244
Lactarius         6961
Hygrocybe         6606
                 ...
Cudonia             28
Heteroradulum       28
Brunneoporus        28
Roridomyces         28
Pulvinula           28
Name: genus, Length: 544, dtype: int64
crispa         1933
versicolor     1821
pinicola       1569
fasciculare    1472
quercina       1316
               ...
acervatus        28
coronatum        28
rhodoleucus      28
ferrugineum      28
circinans        28
Name: specificEpithet, Length: 1429, dtype: int64
Trametes versicolor       1722
Fomitopsis pinicola       1569
Hypholoma fasciculare     1472
Pluteus cervinus          1228
Fomes fomentarius         1185
                          ...
Coprinopsis urticicola      28
Psathyrella obtusata        28
Lycoperdon mammiforme       28
Hygrocybe intermedia        28
Brunneoporus kuzyanus       28
Name: species, Length: 1549, dtype: int64
2847214327-359070    1
2818066306-282707    1
2625336306-280732    1
2238357164-87341     1
2575121635-204563    1
                    ..
2237857074-75720     1
2413148606-266211    1
2898634370-217209    1
2238576334-111201    1
2238185550-157513    1
Name: ImageUniqueID, Length: 263285, dtype: int64
soil                                              121234
dead wood (including bark)                         67320
wood                                               20268
bark of living trees                               10146
leaf or needle litter                               9997
bark                                                4824
wood and roots of living trees                      3755
mosses                                              3610
stems of herbs, grass etc                           2993
wood chips or mulch                                 2919
living leaves                                       2208
siliceous stone                                     2075
fungi                                               1998
faeces                                              1513
cones                                               1120
stone                                               1046
other substrate                                      934
dead stems of herbs, grass etc                       687
living stems of herbs, grass etc                     572
building stone (e.g. bricks)                         498
peat mosses                                          475
fruits                                               421
calcareous stone                                     327
lichens                                              277
insects                                              258
fire spot                                            153
catkins                                              124
living flowers                                        79
liverworts                                            59
remains of vertebrates (e.g. feathers and fur)        34
Name: Substrate, dtype: int64
Deciduous woodland                                      57723
Mixed woodland (with coniferous and deciduous trees)    44077
Unmanaged deciduous woodland                            30717
coniferous woodland/plantation                          27449
park/churchyard                                         17400
natural grassland                                       16794
garden                                                   7463
Unmanaged coniferous woodland                            6967
roadside                                                 6513
Thorny scrubland                                         6194
lawn                                                     5000
hedgerow                                                 4018
Willow scrubland                                         3884
Bog woodland                                             3701
Forest bog                                               3660
heath                                                    3235
dune                                                     3163
bog                                                      2350
wooded meadow, grazing forest                            2245
salt meadow                                              2021
other habitat                                            1921
meadow                                                   1553
gravel or clay pit                                       1349
Acidic oak woodland                                      1032
rock                                                      432
improved grassland                                        387
fallow field                                              315
ditch                                                     281
fertilized field in rotation                              221
masonry                                                   148
roof                                                      106
Name: Habitat, dtype: int64

## Seasonality

In [110]:
data = data.rename(columns={'EventDate':'date'})

In [112]:
data.columns

Index(['eventDate', 'year', 'month', 'day', 'countryCode', 'locality',
       'taxonID', 'scientificName', 'phylum', 'class', 'order', 'family',
       'genus', 'specificEpithet', 'species', 'ImageUniqueID', 'Substrate',
       'Latitude', 'Longitude', 'CoorUncert', 'Habitat', 'class_id',
       'genus_id', 'family_id'],
      dtype='object')

In [111]:
data['date'] = pd.to_datetime(data['date'])

KeyError: 'date'

In [9]:
def season(date):
    if date.month >= 12 and date.day >= 21 or date.month <= 3 and date.day < 21:
        return 1
    elif date.month >= 3 and date.day >= 21 or date.month <= 6 and date.day < 21:
        return 2
    elif date.month >= 6 and date.day >= 21 or date.month <= 9 and date.day < 21:
        return 3
    else:
        return 4

data['season_num'] = data['date'].map(lambda x: season(x))

In [10]:
data['season_cat'] = data['season_num'].map({1:'Winter',
                                            2: 'Spring',
                                            3: 'Summer',
                                            4: 'Winter'})
data['season_cat']

0         Spring
1         Winter
2         Spring
3         Spring
4         Spring
           ...
266339    Spring
266340    Spring
266341    Summer
266342    Winter
266343    Spring
Name: season_cat, Length: 266344, dtype: object

In [39]:
dates = data[['family','month']].groupby(by='month').count().reset_index()
dates['month']= dates['month'].map({1:'January', 2:'February', 3:'March', 4:'April', 5:'May', 6:'June',
                                    7:'July',8:'August', 9:'September', 10:'October', 11:'November', 12:'December'})
dates

        month  family
0     January   13607
1    February    9990
2       March   11309
3       April    9215
4         May    9499
5        June   10092
6        July   16286
7      August   26708
8   September   54215
9     October   62276
10   November   30476
11   December   12655

In [54]:
data = data[data['kingdom']=='Fungi']
data.drop(columns='kingdom',inplace=True)

In [48]:
from ipywidgets import interact

@interact
plt.figure(figsize=(15,8))
sns.barplot(x='month',y='family',data=dates, palette='viridis');

SyntaxError: invalid syntax (<ipython-input-48-0abc0e0dd021>, line 3)

In [49]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.express as px

token = open("pk.eyJ1IjoiaGFkcmk5NiIsImEiOiJja3B4cHV6d24wMDFjMzBqc29neXgyb2VqIn0.ju_WsYC12VK2eTCNNs1aCg").read()

df = px.data.election()

FileNotFoundError: [Errno 2] No such file or directory: 'pk.eyJ1IjoiaGFkcmk5NiIsImEiOiJja3B4cHV6d24wMDFjMzBqc29neXgyb2VqIn0.ju_WsYC12VK2eTCNNs1aCg'

In [ ]:
geojson = px.data.election_geojson()
candidates = df.winner.unique()

app = dash.Dash(__name__)

app.layout = html.Div([
    html.P("Candidate:"),
    dcc.RadioItems(
        id='candidate', 
        options=[{'value': x, 'label': x} 
                 for x in candidates],
        value=candidates[0],
        labelStyle={'display': 'inline-block'}
    ),
    dcc.Graph(id="choropleth"),
])

@app.callback(
    Output("choropleth", "figure"), 
    [Input("candidate", "value")])
def display_choropleth(candidate):
    fig = px.choropleth_mapbox(
        df, geojson=geojson, color=candidate,
        locations="district", featureidkey="properties.district",
        center={"lat": 45.5517, "lon": -73.7073}, zoom=9,
        range_color=[0, 6500])
    fig.update_layout(
        margin={"r":0,"t":0,"l":0,"b":0},
        mapbox_accesstoken=token)

    return fig

app.run_server(debug=True)