In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [39]:
data = pd.read_csv('DanishFungi2020_train_metadata_DEV.csv')
data

,gbifID,eventDate,year,month,day,countryCode,locality,identifiedBy,taxonID,scientificName,...,Substrate,rightsHolder,Latitude,Longitude,CoorUncert,Habitat,image_path,class_id,genus_id,family_id
0,2238546328,2018-04-16T00:00:00,2018.0,4.0,16.0,DK,Ulvedal Plantage,Ulfva Melchior Hvidegaard,30872.0,Ramalina farinacea (L.) Ach.,...,bark of living trees,Ulfva Melchior Hvidegaard,56.299706,9.258110,50.0,Mixed woodland (with coniferous and deciduous ...,/Datasets/DF20/2238546328-30620.jpg,1273,453,142
1,2558871973,2020-01-03T00:00:00,2020.0,1.0,3.0,DK,Slotshegn,Thomas Læssøe,15256.0,Hysterium acuminatum Fr.,...,dead wood (including bark),Ole Martin,55.861899,11.975973,50.0,Deciduous woodland,/Datasets/DF20/2558871973-53941.jpg,708,246,82
2,2238503501,2017-08-22T00:00:00,2017.0,8.0,22.0,DK,Petersborg Strandenge,Per Taudal Poulsen,61200.0,Gliophorus perplexus (A.H.Sm. & Hesler) Kovalenko,...,soil,Per Taudal Poulsen,56.975158,9.285525,75.0,natural grassland,/Datasets/DF20/2238503501-245559.jpg,535,186,76
3,2446759075,2019-10-26T00:00:00,2019.0,10.0,26.0,DK,Klintebjerg,Susanne Rabenborg,30530.0,Lecidella scabra (Taylor) Hertel & Leuckert,...,stone,Susanne Rabenborg,55.960242,11.583103,15.0,gravel or clay pit,/Datasets/DF20/2446759075-197643.jpg,832,276,87
4,2238472345,2016-08-21T00:00:00,2016.0,8.0,21.0,DK,Blåbjerg,Tom Smidth,63728.0,"Russula fragilis Fr., 1838",...,soil,Tom Smidth,55.742985,8.250188,50.0,Mixed woodland (with coniferous and deciduous ...,/Datasets/DF20/2238472345-167057.jpg,1338,476,152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266339,2238575234,2018-10-24T00:00:00,2018.0,10.0,24.0,DK,Glostrup Hospital,Thomas Kehlet,12634.0,Cortinarius subpurpurascens (Batsch) Fr.,...,soil,Thomas Kehlet,55.673710,12.391151,5.0,park/churchyard,/Datasets/DF20/2238575234-110923.jpg,327,111,40
266340,2238488482,2017-04-13T00:00:00,2017.0,4.0,13.0,DK,Husby Klitplantage,Morten Christensen,14064.0,Fomitopsis pinicola (Sw.) P.Karst.,...,dead wood (including bark),Morten Christensen,56.287286,8.172253,25.0,coniferous woodland/plantation,/Datasets/DF20/2238488482-318617.jpg,492,176,56
266341,2856918355,2020-09-05T00:00:00,2020.0,9.0,5.0,DK,Lynæs,Thomas Kehlet,21632.0,Lycoperdon pratense Pers.,...,soil,Thomas Kehlet,55.952711,11.876095,5.0,gravel or clay pit,/Datasets/DF20/2856918355-210091.jpg,886,302,2
266342,2238432527,2009-10-14T00:00:00,2009.0,10.0,14.0,DK,Hylke,Jens Mårbjerg,20599.0,Steccherinum fimbriatum (Pers.) J.Erikss.,...,wood,Jens Mårbjerg,56.006130,9.928160,25.0,Unmanaged deciduous woodland,/Datasets/DF20/2238432527-313815.jpg,1427,504,100
266343,2238546801,2018-05-23T00:00:00,2018.0,5.0,23.0,DK,Roskilde Øst,Tom Smidth,30766.0,Physcia adscendens (Th.Fr.) H.Olivier,...,bark of living trees,Tom Smidth,55.643983,12.100445,25.0,park/churchyard,/Datasets/DF20/2238546801-252985.jpg,1160,408,130

In [40]:
data.isnull().sum().sort_values(ascending=False)/len(data)

infraspecificEpithet    1.000000
CoorUncert              0.012991
identifiedBy            0.006499
Substrate               0.005136
level2Name              0.004107
level2Gid               0.004107
level1Name              0.004025
level1Gid               0.004025
level0Name              0.004025
level0Gid               0.004025
Habitat                 0.003661
order                   0.000589
locality                0.000267
class                   0.000109
species                 0.000109
eventDate               0.000060
day                     0.000060
month                   0.000060
year                    0.000060
image_url               0.000000
Longitude               0.000000
Latitude                0.000000
rightsHolder            0.000000
image_path              0.000000
class_id                0.000000
genus_id                0.000000
gbifID                  0.000000
ImageUniqueID           0.000000
taxonRank               0.000000
specificEpithet         0.000000
genus                   0.000000
family                  0.000000
phylum                  0.000000
kingdom                 0.000000
scientificName          0.000000
taxonID                 0.000000
countryCode             0.000000
family_id               0.000000
dtype: float64

In [41]:
## Select columns, excluding objects
input_cat = data.select_dtypes(exclude=["float64","int64"])
## Store the column names in a variable
features = input_cat.columns
## Loop over all the selected columns to display value_counts
for feature in features:
   print(data[feature].value_counts())

2020-10-31T00:00:00    1013
2020-10-04T00:00:00    1009
2020-10-03T00:00:00    1007
2020-10-11T00:00:00     900
2020-10-09T00:00:00     842
                       ...
1982-08-23T00:00:00       1
2005-08-12T00:00:00       1
2008-07-23T00:00:00       1
1989-10-21T00:00:00       1
2008-04-26T00:00:00       1
Name: eventDate, Length: 5025, dtype: int64
DK    264082
SE      1156
ES       145
GR       142
DE       135
CZ       123
GB       101
NO        99
PL        97
IS        47
IT        35
FI        33
NL        30
FR        30
GL        17
US        14
AU        13
SJ         8
HU         7
PT         6
HR         6
CA         4
FO         3
JP         3
GA         2
AT         2
NP         1
RU         1
CR         1
AL         1
Name: countryCode, dtype: int64
Store Hareskov           2772
Hegedal                  2647
Rantzausminde            2352
Hobro                    2240
Vestskoven, København    1986
                         ...
Tingbjerg                   1
Munkegårde                  1
Vognslund Plantage          1
Kolding Kirkeskov           1
Hesselmose Skov             1
Name: locality, Length: 8861, dtype: int64
Thomas Læssøe          24433
Dan Schou               9446
Tom Smidth              8503
Thomas Kehlet           8298
Arne Pedersen           7664
                       ...
Thomas Black               1
Jan                        1
Beate Strandberg           1
Thomas Hørup Ebling        1
Palle Sørensen             1
Name: identifiedBy, Length: 1802, dtype: int64
Trametes versicolor (L.) Lloyd                                          1722
Fomitopsis pinicola (Sw.) P.Karst.                                      1569
Hypholoma fasciculare (Huds.) P.Kumm., 1871                             1472
Pluteus cervinus (Schaeff.) P.Kumm.                                     1228
Fomes fomentarius (L.) Fr., 1849                                        1185
                                                                        ...
Erysiphe heraclei DC.                                                     28
Cudonia circinans (Pers.) Fr.                                             28
Coprinopsis urticicola (Berk. & Broome) Redhead, Vilgalys & Moncalvo      28
Scutellinia hirta (Schumach.) Cooke, 1876                                 28
Brunneoporus kuzyanus (Pilát) Audet, 2017                                 28
Name: scientificName, Length: 1604, dtype: int64
Fungi        263285
Protozoa       2970
Chromista        89
Name: kingdom, dtype: int64
Basidiomycota    224148
Ascomycota        39031
Mycetozoa          2970
Zygomycota          106
Oomycota             89
Name: phylum, dtype: int64
Agaricomycetes        217875
Lecanoromycetes        16389
Sordariomycetes         8352
Leotiomycetes           6211
Pezizomycetes           5428
Myxomycetes             2756
Pucciniomycetes         2431
Dacrymycetes            1843
Tremellomycetes         1503
Geoglossomycetes        1264
Dothideomycetes          498
Eurotiomycetes           343
Taphrinomycetes          337
Protosteliomycetes       214
Ustilaginomycetes        158
Exobasidiomycetes        152
Orbiliomycetes           130
Atractiellomycetes       118
Mucoromycetes            106
Peronosporea              89
Microbotryomycetes        68
Arthoniomycetes           50
Name: class, dtype: int64
Agaricales       120857
Polyporales       30618
Russulales        22982
Boletales         19216
Lecanorales       11324
                  ...
Patellariales        50
Capnodiales          48
Entylomatales        41
Onygenales           37
Acrospermales        36
Name: order, Length: 65, dtype: int64
Russulaceae         17228
Agaricaceae         14256
Tricholomataceae    14120
Polyporaceae        12558
Boletaceae          12230
                    ...
Coniocybaceae          32
Raveneliaceae          32
Melanconidaceae        32
Caloscyphaceae         29
Collemataceae          28
Name: family, Length: 190, dtype: int64
Russula          10232
Mycena            9325
Cortinarius       7244
Lactarius         6961
Hygrocybe         6606
                 ...
Heteroradulum       28
Roridomyces         28
Cudonia             28
Collema             28
Brunneoporus        28
Name: genus, Length: 566, dtype: int64
crispa           1933
versicolor       1821
pinicola         1569
fasciculare      1472
quercina         1316
                 ...
campanula          28
schistophilum      28
tenax              28
acervatus          28
fuscescens         28
Name: specificEpithet, Length: 1448, dtype: int64
SPECIES    266344
Name: taxonRank, dtype: int64
Trametes versicolor      1722
Fomitopsis pinicola      1569
Hypholoma fasciculare    1472
Pluteus cervinus         1228
Fomes fomentarius        1185
                         ...
Hygrocybe intermedia       28
Calyptella campanula       28
Collema tenax              28
Podosphaera aphanis        28
Clavaria fragilis          28
Name: species, Length: 1577, dtype: int64
DNK    263023
SWE      1151
ESP       144
GRC       142
DEU       140
CZE       123
GBR       101
NOR        99
POL        97
ISL        38
ITA        35
FRA        30
NLD        27
FIN        26
USA        14
GRL        14
AUS        13
GAB         9
SJM         8
HUN         7
HRV         6
PRT         6
CAN         4
JPN         3
BEL         3
FRO         3
AUT         2
ALB         1
NPL         1
CRI         1
RUS         1
Name: level0Gid, dtype: int64
Denmark                   263023
Sweden                      1151
Spain                        144
Greece                       142
Germany                      140
Czech Republic               123
United Kingdom               101
Norway                        99
Poland                        97
Iceland                       38
Italy                         35
France                        30
Netherlands                   27
Finland                       26
Greenland                     14
United States                 14
Australia                     13
Gabon                          9
Svalbard and Jan Mayen         8
Hungary                        7
Croatia                        6
Portugal                       6
Canada                         4
Belgium                        3
Japan                          3
Faroe Islands                  3
Austria                        2
Albania                        1
Russia                         1
Nepal                          1
Costa Rica                     1
Name: level0Name, dtype: int64
DNK.1_1     74583
DNK.2_1     55499
DNK.4_1     48849
DNK.5_1     45918
DNK.3_1     38174
            ...
RUS.33_1        1
ESP.11_1        1
HRV.14_1        1
FRA.5_1         1
AUT.5_1         1
Name: level1Gid, Length: 111, dtype: int64
Hovedstaden              74583
Midtjylland              55499
Sjælland                 48849
Syddanmark               45918
Nordjylland              38174
                         ...
Crete                        1
Baden-Württemberg            1
Salzburg                     1
Friuli-Venezia Giulia        1
Puntarenas                   1
Name: level1Name, Length: 111, dtype: int64
DNK.1.16_1     12651
DNK.5.18_1     11473
DNK.4.3_1       9758
DNK.2.14_1      9719
DNK.2.18_1      8668
               ...
SWE.13.24_1        1
AUS.10.79_1        1
HRV.14.4_1         1
NOR.6.21_1         1
ITA.14.4_1         1
Name: level2Gid, Length: 310, dtype: int64
Gribskov           12651
Svendborg          11473
Guldborgsund        9758
Silkeborg           9719
Syddjurs            8668
                   ...
Carmarthenshire        1
Udine                  1
Šumperk                1
Tavastia Proper        1
Simrishamn             1
Name: level2Name, Length: 310, dtype: int64
2238561563-33853     1
2556151295-202613    1
2874306516-289187    1
2248039715-188495    1
2449442967-347917    1
                    ..
2238226118-11105     1
2238483228-20141     1
2986454337-371651    1
2421821609-119141    1
2549107337-351512    1
Name: ImageUniqueID, Length: 266344, dtype: int64
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/jan/PH99-033.JPG                2
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/jan/JV86-221.JPG                2
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/2020-10130796_r1eifnEPP.JPG     1
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/2020-10118938_rkAJdV7LP.JPG     1
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/2020-10134899_HkGOrS2vP.JPG     1
                                                                                                         ..
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/2020-10076545_BkmHxCbKxL.JPG    1
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/2019-10001916_SJExMdh7N.JPG     1
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/2020-10111444_SyZa9hmBP.JPG     1
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/EAT2013PIC81017697.JPG          1
https://api.gbif.org/v1/image/unsafe/https://svampe.databasen.org/uploads/2018-9330099_rkGAlE39dX.JPG     1
Name: image_url, Length: 266342, dtype: int64
soil                                              121280
dead wood (including bark)                         69316
wood                                               20694
bark of living trees                               10213
leaf or needle litter                              10089
bark                                                4911
wood and roots of living trees                      3773
mosses                                              3659
stems of herbs, grass etc                           3053
wood chips or mulch                                 2963
living leaves                                       2292
siliceous stone                                     2075
fungi                                               2022
faeces                                              1526
cones                                               1120
stone                                               1052
other substrate                                      937
dead stems of herbs, grass etc                       688
living stems of herbs, grass etc                     598
building stone (e.g. bricks)                         498
peat mosses                                          481
fruits                                               423
calcareous stone                                     327
lichens                                              277
insects                                              258
fire spot                                            153
catkins                                              124
living flowers                                        79
liverworts                                            59
remains of vertebrates (e.g. feathers and fur)        34
mycetozoans                                            2
Name: Substrate, dtype: int64
Tom Smidth             11632
Dan Schou              11481
Arne Pedersen          10531
Thomas Kehlet           6676
Bjørn W. Pedersen       6166
                       ...
Kjeld Gammelgaard          1
Iben Førby                 1
Morten Sørensen            1
Martin Bo Hermansen        1
Palle Sørensen             1
Name: rightsHolder, Length: 2030, dtype: int64
Deciduous woodland                                      58393
Mixed woodland (with coniferous and deciduous trees)    44779
Unmanaged deciduous woodland                            31267
coniferous woodland/plantation                          27724
park/churchyard                                         17474
natural grassland                                       16843
garden                                                   7551
Unmanaged coniferous woodland                            7108
roadside                                                 6562
Thorny scrubland                                         6290
lawn                                                     5025
hedgerow                                                 4063
Willow scrubland                                         3918
Bog woodland                                             3772
Forest bog                                               3694
heath                                                    3240
dune                                                     3166
bog                                                      2397
wooded meadow, grazing forest                            2275
salt meadow                                              2024
other habitat                                            1940
meadow                                                   1572
gravel or clay pit                                       1361
Acidic oak woodland                                      1036
rock                                                      432
improved grassland                                        387
fallow field                                              317
ditch                                                     284
fertilized field in rotation                              221
masonry                                                   148
roof                                                      106
Name: Habitat, dtype: int64

/Datasets/DF20/2238502998-23374.jpg     1
/Datasets/DF20/2994402331-297763.jpg    1
/Datasets/DF20/2818064335-208268.jpg    1
/Datasets/DF20/2238498330-170770.jpg    1
/Datasets/DF20/2556150912-351760.jpg    1
                                       ..
/Datasets/DF20/2862702454-137619.jpg    1
/Datasets/DF20/2238502827-320788.jpg    1
/Datasets/DF20/2238574325-184691.jpg    1
/Datasets/DF20/2238493220-169968.jpg    1
/Datasets/DF20/2883260476-290336.jpg    1
Name: image_path, Length: 266344, dtype: int64

In [42]:
data.drop(columns=['image_path','rightsHolder','image_url',
                   'identifiedBy','eventDate','infraspecificEpithet',
                  'level0Gid','level0Name', 'level1Gid', 'level1Name', 
                   'level2Gid', 'level2Name'], inplace=True)

data.columns

Index(['gbifID', 'year', 'month', 'day', 'countryCode', 'locality', 'taxonID',
       'scientificName', 'kingdom', 'phylum', 'class', 'order', 'family',
       'genus', 'specificEpithet', 'taxonRank', 'species', 'ImageUniqueID',
       'Substrate', 'Latitude', 'Longitude', 'CoorUncert', 'Habitat',
       'class_id', 'genus_id', 'family_id'],
      dtype='object')

In [43]:
data.describe()

,gbifID,year,month,day,taxonID,Latitude,Longitude,CoorUncert,class_id,genus_id,family_id
count,2.663440e+05,266328.000000,266328.000000,266328.000000,266344.000000,266344.000000,266344.000000,262884.000000,266344.000000,266344.000000,266344.000000
mean,2.426318e+09,2017.078655,8.027237,15.767490,25194.488980,55.837151,10.931049,79.902059,796.512792,278.982429,94.325290
std,2.595430e+08,3.611341,2.988485,8.812455,17815.818491,1.259866,2.313764,580.372146,467.585410,163.746126,54.774401
min,2.237852e+09,1874.000000,1.000000,1.000000,10000.000000,-42.866439,-149.905597,1.000000,0.000000,0.000000,0.000000
25%,2.238468e+09,2016.000000,7.000000,8.000000,14394.000000,55.479529,9.799603,15.000000,387.000000,132.000000,51.000000
50%,2.238573e+09,2018.000000,9.000000,16.000000,17968.000000,55.816564,10.639701,25.000000,790.000000,263.000000,100.000000
75%,2.575119e+09,2020.000000,10.000000,23.000000,21777.000000,56.163745,12.211229,50.000000,1184.000000,420.000000,137.000000
max,2.994406e+09,2020.000000,12.000000,31.000000,70068.000000,78.217562,147.330200,130251.000000,1603.000000,565.000000,189.000000

## Seasonality

In [45]:
data['date'] = data[data.columns[1:4]].apply(
    lambda x: '-'.join(x.dropna().astype(int).astype(str)),
    axis=1
)
data['date']

0          2018-4-16
1           2020-1-3
2          2017-8-22
3         2019-10-26
4          2016-8-21
             ...
266339    2018-10-24
266340     2017-4-13
266341      2020-9-5
266342    2009-10-14
266343     2018-5-23
Name: date, Length: 266344, dtype: object

In [46]:
data['date'] = pd.to_datetime(data['date'])

In [61]:
def season(date):
    if date.month >= 12 and date.day >= 21 or date.month <= 3 and date.day < 21:
        return 1
    elif date.month >= 3 and date.day >= 21 or date.month <= 6 and date.day < 21:
        return 2
    elif date.month >= 6 and date.day >= 21 or date.month <= 9 and date.day < 21:
        return 3
    else:
        return 4

data['season_num'] = data['date'].map(lambda x: season(x))

In [63]:
data['season_cat'] = data['season_num'].map({1:'Winter',
                                            2: 'Spring',
                                            3: 'Summer',
                                            4: 'Winter'})
data['season_cat']

0         Spring
1         Winter
2         Spring
3         Spring
4         Spring
           ...
266339    Spring
266340    Spring
266341    Summer
266342    Winter
266343    Spring
Name: season_cat, Length: 266344, dtype: object

In [67]:
fig = px.scatter(data, x="month", color="Habitat")

KeyError: (nan, '', '', '', '')